
version: '3.10'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: social_app
    volumes:
      - .:/social_app
    ports:
      - "8000:8000"

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: 

